name = "HashCode2014Solution"
uuid = "605baa05-9b92-4307-bf47-0bd49f0fb794"
authors = ["Yuval Mamana <yuvalm11@mit.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
